name: tracktion
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.22.0
  flutter_bloc: ^7.2.0
  http: ^0.13.3 
  cupertino_icons: ^1.0.0
  shared_preferences: ^2.0.5
  connectivity: ^3.0.3
  moor: ^4.2.1
  path_provider: ^2.0.1
  moor_flutter: ^4.0.0
  fl_chart: ^0.36.0 
  firebase_core: "^1.1.0"
  firebase_auth: "^1.1.3"
  flutter_staggered_grid_view: ^0.3.3
  sqlite3_flutter_libs: ^0.4.1
  union: ^0.0.3+1
  intl: ^0.17.0
  google_sign_in: "^4.5.1"
  flutter_facebook_auth: ^1.0.0
  flutter_twitter_login: ^1.1.0
  font_awesome_flutter: ^8.11.0
  modal_bottom_sheet: ^1.0.0+1
  table_calendar: ^3.0.2
  # flutter_cupertino_date_picker: ^1.0.26+2
    # git:
    #   url: https://github.com/imshashank/flutter-cupertino-date-picker # Repo
    #   ref: master
 
  path: ^1.6.4
  undo: ^1.3.0+1
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  moor_generator: ^4.2.2
  build_runner: ^1.10.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/vectors/home.svg
    - assets/vectors/abs.svg
    - assets/vectors/back.svg
    - assets/vectors/butt.svg
    - assets/vectors/calfs.svg
    - assets/vectors/chest.svg
    - assets/vectors/hamstrings.svg
    - assets/vectors/legs.svg
    - assets/vectors/quads.svg
    - assets/vectors/shoulders.svg
    - assets/vectors/arms.svg
    - assets/vectors/routines/1.svg
    - assets/vectors/routines/2.svg
    - assets/vectors/routines/3.svg
    - assets/vectors/routines/4.svg
    - assets/vectors/routines/5.svg
    - assets/vectors/routines/6.svg
    - assets/icons/google_light.png
    - assets/poses/1.svg
    - assets/poses/2.svg
    - assets/poses/3.svg
    - assets/poses/4.svg
    - assets/poses/5.svg
    - assets/poses/6.svg
    - assets/poses/7.svg
    - assets/poses/8.svg
    - assets/poses/9.svg

  fonts:
    - family: CarterOne
      fonts:
        - asset: assets/fonts/CarterOne-Regular.ttf
